bot:
    # Bot token.
    token: "<add-token-here>"
    # ID of the Discord server
    server-id: 000000000000000000
    # Decides what messages are shown in console
    # Possible values are: Critical, Error, Warning, Information, Debug.
    console-log-level: "Information"
    # Sets the type of activity for the bot to display in its presence status
    # Possible values are: Playing, Streaming, ListeningTo, Watching, Competing
    presence-type: "ListeningTo"
    # Sets the activity text shown in the bot's status
    presence-text: "/join"

# Set up which roles are allowed to use different commands.
# Example:
#   join: [ 000000000000000000, 111111111111111111 ]
# They are grouped into suggested command groups below for first time setup.
permissions:
    # Public commands
    join: []
    leave: []
    help: []
    # Moderator commands
    ping: []
    # Admin commands
    addrole: []
    removerole: []